### ISSUE TITLE
Time slowing when hiding bug

### ISSUE THREAD

**Issue by himchawla** [Rellik-Studios/Production#275]

**Comment by RachaelColaco** [comment]
I checked but I saw the bug happening still and it is much worst when you hide in a red indicator after this everything is slow in gameplay.

**Comment by RachaelColaco** [comment]
![image](https://user-images.githubusercontent.com/65530256/160726888-ccd6f43d-2659-4395-9250-44fc72ae1d97.png)
This is the issue @himchawla
