### ISSUE TITLE
Doors for futuristic after entering are acting strange

### ISSUE THREAD

**Issue by RachaelColaco** [Rellik-Studios/Production#285]
When entering the first room and trying to exit (after completing objective) there is something that blocks you out from exiting. And worst the safe room trigger gets enabled but you teleport outside behind the saferoom into the other room.

**Comment by himchawla** [comment]
hmm, you mentioned this in the bug log channel as well, is this fixed?

**Comment by RachaelColaco** [comment]
I just did I just wanted to write it in the github for reference. Its fixed now
